/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:56b083c8-10f6-4205-9ef8-306ba7a3f529",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Si3O6cTWF",
    "aws_user_pools_web_client_id": "7teksqc8260qg1ei4vcrohmhd5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dpkxubprvvbf7ng3periuvtucu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dtlnfuuvcbculctzrtxpfezmna"
};


export default awsmobile;
